# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-26 04:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_auto_20171125_1700'),
    ]

    operations = [
        migrations.AddField(
            model_name='investigacion',
            name='archivo',
            field=models.FileField(blank=True, upload_to='uploads/%Y/%m/%d/'),
        ),
        migrations.AddField(
            model_name='investigacion',
            name='autor',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
